/**
 * The domain map: a generated partition of the documented files into named
 * subsystems. It is the source of truth for the second documentation tier and
 * lives in state (`.codelore/domains.codelore.json`), regenerated by the
 * partition pass and maintained incrementally — never hand-edited as policy,
 * though a manual edit is respected like any state edit.
 */
export const DOMAIN_MAP_VERSION = 1;

export interface DomainMapEntry {
  /** Stable ascii identifier; drives the domain id, doc path, and anchor. */
  slug: string;
  /** Display heading, in the canonical doc language. */
  name: string;
  /** Member source-file paths (project-relative). */
  files: string[];
  /** One line on why these files form a subsystem; carried for humans and re-partition context. */
  rationale?: string;
}

export interface DomainMap {
  version: number;
  generatedAt: string;
  domains: DomainMapEntry[];
}

/** file path → its domain slug. A file assigned to two domains keeps the first (coverage check flags it). */
export function fileToDomainSlug(map: DomainMap): Map<string, string> {
  const byFile = new Map<string, string>();
  for (const domain of map.domains) {
    for (const file of domain.files) {
      if (!byFile.has(file)) {
        byFile.set(file, domain.slug);
      }
    }
  }
  return byFile;
}

export interface DomainCoverage {
  /** Documented files assigned to no domain. */
  uncovered: string[];
  /** Files assigned to more than one domain, with the offending slugs. */
  doubleAssigned: Array<{ file: string; slugs: string[] }>;
  /** Domain files that are not documented (no member doc to summarise from). */
  danglingFiles: Array<{ slug: string; file: string }>;
}

/**
 * Coverage of `documentedFiles` (the files that have a doc) against the map:
 * which are unassigned, which are double-assigned, and which map entries point at
 * files that are not documented. All deterministic set arithmetic — the check
 * surface for map drift, no LLM.
 */
export function domainCoverage(map: DomainMap, documentedFiles: Iterable<string>): DomainCoverage {
  const documented = new Set(documentedFiles);
  const slugsByFile = new Map<string, string[]>();
  const danglingFiles: DomainCoverage["danglingFiles"] = [];
  for (const domain of map.domains) {
    for (const file of domain.files) {
      const slugs = slugsByFile.get(file) ?? [];
      slugs.push(domain.slug);
      slugsByFile.set(file, slugs);
      if (!documented.has(file)) {
        danglingFiles.push({ slug: domain.slug, file });
      }
    }
  }

  const uncovered: string[] = [];
  for (const file of documented) {
    if (!slugsByFile.has(file)) {
      uncovered.push(file);
    }
  }

  const doubleAssigned: DomainCoverage["doubleAssigned"] = [];
  for (const [file, slugs] of slugsByFile) {
    if (slugs.length > 1) {
      doubleAssigned.push({ file, slugs: [...slugs].sort() });
    }
  }

  return {
    uncovered: uncovered.sort(),
    doubleAssigned: doubleAssigned.sort((a, b) => a.file.localeCompare(b.file)),
    danglingFiles: danglingFiles.sort((a, b) => a.file.localeCompare(b.file)),
  };
}
